apiVersion: v1
kind: Service
metadata:
  name: chat-demo-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: chat-demo-frontend-dep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
