apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-demo-frontend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-demo-frontend-dep
  template:
    metadata:
      labels:
        app: chat-demo-frontend-dep
    spec:
      containers:
        - name: chat-demo-frontend
          image: ghcr.io/akablockchain2/chat-demo-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://aebf4c1d40ead4780871c643f6bf14b8-700165815.us-east-1.elb.amazonaws.com:80"
